### ISSUE TITLE
Write doc about file based configuration for kamel CLI

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-k#1155] opened 2019-12-18 11:23 UTC
@lburgazzoli , @valdar

**Comment by squakez** [comment] 2021-01-12 09:30
I was having a look at this. I am wondering if the issue is about the `--config` flag and where the documentation should go. @nicolaferraro do you mind clarifying that?

**Comment by Gre8t** [comment] 2022-03-28 16:21
Hi, I also looked through this and did not find any --config flag. Could you please elaborate more, so I can start documenting?

**Comment by Gre8t** [comment] 2022-03-28 16:21
@astefanutti

**Comment by astefanutti** [comment] 2022-03-28 16:45
@Gre8t I don't think this is about any `--config` flag.

This is about the Viper configuration, that can be stored locally and managed with: 

https://github.com/apache/camel-k/blob/dab66604c12ba81cece7f58819753789517af3b6/pkg/cmd/root.go#L118

And in a couple of places like:

https://github.com/apache/camel-k/blob/dab66604c12ba81cece7f58819753789517af3b6/pkg/cmd/run.go#L365

**Comment by Gre8t** [comment] 2022-03-28 17:48
is there a link to a sample of the configs. And what folder under docs should this documentation be in.

**Comment by astefanutti** [comment] 2022-03-28 17:51
Unfortunately I don't think there is. You should be able to generate it by running commands, the location of the file being driven by:

https://github.com/apache/camel-k/blob/dab66604c12ba81cece7f58819753789517af3b6/pkg/cmd/root.go#L101-L110

**Comment by astefanutti** [comment] 2022-03-28 18:00
I'd suggest to create an new file in https://github.com/apache/camel-k/tree/main/docs/modules/ROOT/pages/cli.

**Comment by astefanutti** [comment] 2022-03-30 14:35
This issue is not about modeline, for which the documentation already exists. It's more about the local CLI configuration file that's generated by Viper.

**Comment by Gre8t** [comment] 2022-03-30 14:48
Still haven't understood, but let me look through the code.

**Comment by Gre8t** [comment] 2022-03-30 20:24
I think I can be able to fix this if I understand what a config file is. Is this an [example](https://github.com/weimeilin79/camel-k-example-event-streaming/blob/c7971a29552c6d418b71aad7ba4aab5b9930164d/kamel-config.yaml) of what a file based configuration looks like

**Comment by Gre8t** [comment] 2022-04-02 07:23
hi, is this an example of what a file based configuration looks like 
![Screenshot from 2022-04-02 08-22-43](https://user-images.githubusercontent.com/20660598/161371987-e24230b9-5437-4c4c-8581-dc4b6b3ff1ce.png)

**Comment by astefanutti** [comment] 2022-04-04 07:31
I think this example is specific to the `local run` and `local build` commands. That issue is more about the generic mechanism provided by Viper and configured here:

https://github.com/apache/camel-k/blob/dab66604c12ba81cece7f58819753789517af3b6/pkg/cmd/root.go#L101-L110

It is documented here: https://github.com/spf13/viper#reading-config-files

**Comment by Gre8t** [comment] 2022-04-06 19:07
If I'm not mistaken, you're referring to the integration file when you say "file-based configuration".

**Comment by tadayosi** [comment] 2022-04-07 01:54
@Gre8t @astefanutti 

If I'm not mistaken, this issue is talking about this feature: #1108  That issue description should give you an idea of what the file based configuration can do with kamel cli.
So in essense, you can pass config parameters to the cli with a config file, just like you do with env vars or cli parameters.

**Comment by Gre8t** [comment] 2022-04-08 08:47
Eureka!!! I think I figured it out. Let me confirm my thoughts first

**Comment by Gre8t** [comment] 2022-04-08 08:58
My documentation is based on these flags in [install.go](https://github.com/apache/camel-k/blob/939bc58356994e401b484a17603dd7f85a8cd1e5/pkg/cmd/install.go#L549).

**Comment by Gre8t** [comment] 2022-04-11 14:28
Hi, can this be assigned to me?

**Comment by astefanutti** [comment] 2022-04-19 07:56
Fixed by #3187.

**Closed by astefanutti** 2022-04-19 07:56 UTC
Labels: good first issue, area/documentation
