### ISSUE TITLE
examples/RestDSL.java does not work

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-k#2349] opened 2021-06-02 13:28 UTC
Reported on chat forum and I could not get it to work either with minkube and camel-k 1.4.0 release
https://camel.zulipchat.com/#narrow/stream/257299-camel-k/topic/Rest-DSL/near/241114457

**Comment by tadayosi** [comment] 2021-06-07 05:44
I couldn't reproduce it with camel-k 1.5.0-SNAPSHOT & minikube v1.20.0. Looking at the chat log, it appears the RestDSL example problem has been solved for him, too. Maybe we can close it?

**Closed** 2021-06-07 07:24 UTC
