### ISSUE TITLE
kamel run simple.js --dev hangs after multiple kill/start

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-k#1505] opened 2020-06-07 21:09 UTC
How to reproduce:
kamel run simple.js --dev
wait for the example to start successfully
CTRL+C

Repeat the 3 steps above 3 times (perhaps more), then it occurs that the example stay stuck with log:
`Condition "Ready" is "True" for Integration simple`
No integration pods looks to be running

**Comment by lburgazzoli** [comment] 2020-06-10 06:40
can you check if there is any unsatisfied condition in the deployment ?

**Comment by aldettinger** [comment] 2020-06-10 10:11
`oc get deployment simple -o json` output below status:
```   
    "status": {
        "availableReplicas": 1,
        "conditions": [
            {
                "lastTransitionTime": "2020-06-10T09:18:39Z",
                "lastUpdateTime": "2020-06-10T09:18:39Z",
                "message": "Deployment has minimum availability.",
                "reason": "MinimumReplicasAvailable",
                "status": "True",
                "type": "Available"
            },
            {
                "lastTransitionTime": "2020-06-10T09:18:36Z",
                "lastUpdateTime": "2020-06-10T09:18:39Z",
                "message": "ReplicaSet \"simple-657f4555dd\" has successfully progressed.",
                "reason": "NewReplicaSetAvailable",
                "status": "True",
                "type": "Progressing"
            }
        ],
        "observedGeneration": 1,
        "readyReplicas": 1,
        "replicas": 1,
        "updatedReplicas": 1
    }
```
But, the status looks to be the same whether the example runs fine or hung up.
pod and integration statuses also remain equivalent.

**Comment by tadayosi** [comment] 2020-06-16 04:07
I seem to reproduce the issue, too. I use Camel K 1.1.0-SNAPSHOT and minikube v1.11.0.
```
$ kamel run --dev examples/simple.js
...
Condition "DeploymentAvailable" is "True" for Integration simple: deployment name is simple
Condition "ServiceAvailable" is "False" for Integration simple: no http service required
Condition "ExposureAvailable" is "False" for Integration simple: no host or service defined
Condition "Ready" is "False" for Integration simple
Condition "Ready" is "True" for Integration simple
```

**Comment by tadayosi** [comment] 2020-06-16 04:16
What hangs actually is the `kamel run --dev` session that's supposed to keep output logs. The deployment still runs fine as you can see running logs from another terminal with `kamel log simple`.

**Comment by tadayosi** [comment] 2020-06-22 08:43
@aldettinger @lburgazzoli If no one is working on it yet, I can look into it.

**Comment by aldettinger** [comment] 2020-06-22 20:22
Hey @tadayosi , sure you can :+1:

**Comment by aldettinger** [comment] 2020-06-25 18:31
@tadayosi it seems I can't reproduce with Camel-K 1.0.1, maybe linked to #1558

**Comment by tadayosi** [comment] 2020-06-26 04:06
@aldettinger Yes, thanks to #1558 now cleanup of terminating pods seems to get faster. I think that's the reason why the issue no longer happens as frequently as before (less concurrent reads/writes of the pipe to stdout). I still have a feeling that the root cause is some deadlock at the shared pipe to stdout in the `SelectorScraper`. But for now the issue becomes negligible so let's close it.

**Closed** 2020-06-26 04:07 UTC
