### ISSUE TITLE
Recent testing failures

### ISSUE THREAD

**Issue by squakez** [apache/camel-k#3861] opened 2022-11-30 13:48 UTC
Recently we are having a couple of tests failing within the `install` workflow: https://github.com/apache/camel-k/actions/runs/3582747159/jobs/6027336970

❌ TestBasicSetup (1m13.94s)
  No IntegrationPlatform resource in default namespace
...
  Camel K Cluster Roles removed from cluster
  Using alternative make directory on path ../../../../install
  Using alternative make directory on path ../../../../install
      setup_test.go:51: 
          Timed out after 60.003s.
          Expected
              <[]v1.Role | len:0, cap:0>: nil
          To satisfy at least one of these matchers: [%!s(*matchers.HaveLenMatcher=&{7}) %!s(*matchers.HaveLenMatcher=&{8})]

❌ TestGlobalSetup (1m13.26s)
  No IntegrationPlatform resource in default namespace
  ...
  Using alternative make directory on path ../../../../install
  Using alternative make directory on path ../../../../install
      setup_test.go:78: 
          Timed out after 60.003s.
          Expected
              <[]v1.Role | len:7, cap:8>: [
                  {
                      TypeMeta: {Kind: "", APIVersion: ""},
                      ObjectMeta: {

**Comment by squakez** [comment] 2022-11-30 13:50
I can see that even the successful tests of the same workflow report:
```
  Camel K Cluster Roles removed from cluster
  Using alternative make directory on path ../../../../install
  Using alternative make directory on path ../../../../install
  Using alternative make directory on path ../../../../install
      test_support.go:2239: Warning: some pods are still running in namespace "test-937a699e-8c7f-4ed4-8402-d82a9750213e" after deletion (1)
```
I wonder if this is the root cause.

**Comment by tadayosi** [comment] 2022-12-01 04:06
This is a duplicate of #3772. I'm already working on it.

For now, what I see as the possible root cause is that `kustomize` taints `kustomization.yaml` under `install/` each test run and it could be that the installation scripts are not idempotent, so the random order of test executions sometimes cause misconfigurations.

**Closed** 2022-12-01 08:12 UTC
Labels: area/continuous integration, area/test
