### ISSUE TITLE
routes-rest.js not working

### ISSUE THREAD

**Issue by waytoharish** [apache/camel-k#1174] opened 2019-12-30 22:34 UTC
Hi, 
I am trying to run the example code in  routes-rest.js but getting bellow error-

{"level":"info","ts":1577614671.9545598,"logger":"camel-k.controller.integration","msg":"Reconciling Integration","request-namespace":"myproject","request-name":"withrest"}
{"level":"info","ts":1577614671.9546976,"logger":"camel-k.controller.integration","msg":"Invoking action deploy","request-namespace":"myproject","request-name":"withrest","api-version":"camel.apache.org/v1","kind":"Integration","ns":"myproject","name":"withrest"}
{"level":"info","ts":1577614671.9551828,"logger":"camel-k.trait","msg":"Apply trait: camel"}
{"level":"info","ts":1577614671.9585996,"logger":"camel-k.trait","msg":"Apply trait: knative"}
{"level":"info","ts":1577614671.9586687,"logger":"camel-k.trait","msg":"Apply trait: environment"}
{"level":"info","ts":1577614671.9586837,"logger":"camel-k.trait","msg":"Apply trait: deployer"}
{"level":"info","ts":1577614671.958994,"logger":"camel-k.trait","msg":"Apply trait: gc"}
{"level":"info","ts":1577614671.9596505,"logger":"camel-k.trait","msg":"Apply trait: knative-service"}
{"level":"info","ts":1577614671.9597151,"logger":"camel-k.trait","msg":"Apply trait: container"}
{"level":"info","ts":1577614671.9597356,"logger":"camel-k.traits","msg":"Environment variable POD_NAME uses fieldRef and cannot be set on a Knative service","trait":"container"}
{"level":"info","ts":1577614671.9597497,"logger":"camel-k.trait","msg":"Apply trait: jolokia"}
{"level":"info","ts":1577614671.9597564,"logger":"camel-k.trait","msg":"Apply trait: prometheus"}
{"level":"info","ts":1577614671.9597611,"logger":"camel-k.trait","msg":"Apply trait: classpath"}
{"level":"info","ts":1577614671.9597938,"logger":"camel-k.trait","msg":"Apply trait: owner"}
{"level":"error","ts":1577614673.2611904,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"integration-controller","request":"myproject/withrest","error":"error executing post actions: error during replace resource: could not create or replace resource withrest: no matches for kind \"Service\" in version \"serving.knative.dev/v1\"","errorVerbose":"no matches for kind \"Service\" in version \"serving.knative.dev/v1\"\ncould not create or replace resource withrest\ngithub.com/apache/camel-k/pkg/util/kubernetes.ReplaceResource\n\tgithub.com/apache/camel-k@/pkg/util/kubernetes/replace.go:69\ngithub.com/apache/camel-k/pkg/util/kubernetes.ReplaceResources\n\tgithub.com/apache/camel-k@/pkg/util/kubernetes/replace.go:38\ngithub.com/apache/camel-k/pkg/trait.(*deployerTrait).Apply.func1\n\tgithub.com/apache/camel-k@/pkg/trait/deployer.go:64\ngithub.com/apache/camel-k/pkg/trait.Apply\n\tgithub.com/apache/camel-k@/pkg/trait/trait.go:52\ngithub.com/apache/camel-k/pkg/controller/integration.(*deployAction).Handle\n\tgithub.com/apache/camel-k@/pkg/controller/integration/deploy.go:56\ngithub.com/apache/camel-k/pkg/controller/integration.(*ReconcileIntegration).Reconcile\n\tgithub.com/apache/camel-k@/pkg/controller/integration/integration_controller.go:257\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tsigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tk8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tk8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:88\nruntime.goexit\n\truntime/asm_amd64.s:1357\nerror during replace resource\ngithub.com/apache/camel-k/pkg/trait.(*deployerTrait).Apply.func1\n\tgithub.com/apache/camel-k@/pkg/trait/deployer.go:65\ngithub.com/apache/camel-k/pkg/trait.Apply\n\tgithub.com/apache/camel-k@/pkg/trait/trait.go:52\ngithub.com/apache/camel-k/pkg/controller/integration.(*deployAction).Handle\n\tgithub.com/apache/camel-k@/pkg/controller/integration/deploy.go:56\ngithub.com/apache/camel-k/pkg/controller/integration.(*ReconcileIntegration).Reconcile\n\tgithub.com/apache/camel-k@/pkg/controller/integration/integration_controller.go:257\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tsigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tk8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tk8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:88\nruntime.goexit\n\truntime/asm_amd64.s:1357\nerror executing post actions\ngithub.com/apache/camel-k/pkg/trait.Apply\n\tgithub.com/apache/camel-k@/pkg/trait/trait.go:54\ngithub.com/apache/camel-k/pkg/controller/integration.(*deployAction).Handle\n\tgithub.com/apache/camel-k@/pkg/controller/integration/deploy.go:56\ngithub.com/apache/camel-k/pkg/controller/integration.(*ReconcileIntegration).Reconcile\n\tgithub.com/apache/camel-k@/pkg/controller/integration/integration_controller.go:257\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tsigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tk8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tk8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:88\nruntime.goexit\n\truntime/asm_amd64.s:1357","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tsigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tk8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tk8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:88"}

**Comment by lburgazzoli** [comment] 2020-01-01 22:13
Seems to be a duplicate of https://github.com/apache/camel-k/issues/1175

**Comment by lburgazzoli** [comment] 2020-06-05 08:06
not an issue anymore

**Closed by lburgazzoli** 2020-06-05 08:06 UTC
