### ISSUE TITLE
RBAC missing permissions for channels and inmemorychannels in messaging.knative.dev

### ISSUE THREAD

**Issue by christophd** [apache/camel-k#3390] opened 2022-06-23 14:49 UTC
The Camel K operator has lost the permission to get/list and manage channels/inmemorychannels in messaging.knative.dev group. This causes the knative trait to raise permission errors when binding a Kamelet to channels/inmemorychannels for instance.

To reproduce add a KameletBinding that makes use of a Knative channel.

```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: message-event-sink
spec:
  source:
    ref:
      kind: Channel
      apiVersion: messaging.knative.dev/v1
      name: messages
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink
```

This will result in errors in Camel K operator logs and the KameletBinding is stuck in "Creating" phase.

```
{"level":"error","ts":1655995698.9808981,"logger":"controller.integration-controller","msg":"Reconciler error","reconciler group":"camel.apache.org","reconciler kind":"Integration","name":"prize-event-sink","namespace":"yaks-demo","error":"error during trait customization: unexpected error while executing handler for channel prize-channel: cannot determine address of channel prize-channel: channels.messaging.knative.dev \"prize-channel\" is forbidden: User \"system:serviceaccount:openshift-operators:camel-k-operator\" cannot get resource \"channels\" in API group \"messaging.knative.dev\" in the namespace \"yaks-demo\"","errorVerbose":"channels.messaging.knative.dev \"prize-channel\" is forbidden: User \"system:serviceaccount:openshift-operators:camel-k-operator\" cannot get resource \"channels\" in API group \"messaging.knative.dev\" in the namespace \"yaks-demo\"\ncannot determine address of channel prize-channel\ngithub.com/apache/camel-k/pkg/trait.(*knativeTrait).withServiceDo.func1\n\tgithub.com/apach...
```

**Comment by phantomjinx** [comment] 2022-06-23 15:20
Fixed in https://github.com/apache/camel-k/pull/3382

**Comment by astefanutti** [comment] 2022-06-23 15:28
Possible duplicate of #3328.

**Comment by christophd** [comment] 2022-06-23 15:34
I think the addressable changes do apply for Knative channels as a sink. I was using the channel as a source in the KameletBinding. Does that make a difference?

**Comment by astefanutti** [comment] 2022-06-23 15:38
I think #2958 should apply whether a Knative Addressable to be resolved is used as a sink or source.

**Comment by christophd** [comment] 2022-06-27 09:39
@astefanutti I can see `{"level":"info","ts":1656322558.1037383,"logger":"cmd","msg":"Cannot bind the Knative Addressable resolver aggregated ClusterRole: skipping."}` in my operator logs. So that is why the addressable-resolver cluster role binding is not present on my cluster.

Need to find out what that exact problem is here

**Closed** 2022-07-01 08:07 UTC
