### ISSUE TITLE
operator-sdk build fails on latest master with 'make images-dev'

### ISSUE THREAD

**Issue by dmvolod** [apache/camel-k#863] opened 2019-07-24 11:53 UTC
Strange operator-sdk build behavior after some latest updates

```
operator-sdk build docker.io/apache/camel-k:1.0.0-M1-SNAPSHOT
build github.com/apache/camel-k/cmd/manager: cannot load github.com/knative/serving/pkg/apis/serving/v1beta1: open /home/dvolodin/go/src/github.com/apache/camel-k/vendor/github.com/knative/serving/pkg/apis/serving/v1beta1: no such file or directory
Error: failed to build operator binary: (failed to exec []string{"go", "build", "-o", "/home/dvolodin/go/src/github.com/apache/camel-k/build/_output/bin/camel-k", "-gcflags", "all=-trimpath=/home/dvolodin/go/src/github.com/apache", "-asmflags", "all=-trimpath=/home/dvolodin/go/src/github.com/apache", "-mod=vendor", "github.com/apache/camel-k/cmd/manager"}: exit status 1)
```

**Comment by astefanutti** [comment] 2019-07-24 12:04
It may be due to `-mod=vendor`, while the build uses Go modules.

**Comment by astefanutti** [comment] 2019-07-24 12:06
You may need to upgrade your Operator SDK binary to latest 0.9.0 version.

**Comment by dmvolod** [comment] 2019-07-24 12:10
@astefanutti i'm on the latest version
[dvolodin@dvolodin camel-k]$ operator-sdk version
operator-sdk version: v0.9.0, commit: 560208dc998de497bbf59fea1b63426aec430934

**Comment by astefanutti** [comment] 2019-07-24 12:12
You need to invoke the Go commands with the environment variable `GO111MODULE=on`, in case you've checked out the repository inside of the `$GOPATH/src` tree.

**Comment by dmvolod** [comment] 2019-07-24 12:17
@astefanutti , I'm using GO111MODULE env variable. It's strange that all were working 2 days ago.

**Comment by astefanutti** [comment] 2019-07-24 12:18
I'm running out of ideas 😉 but that `-mod=vendor` looks suspicious to me.

**Comment by dmvolod** [comment] 2019-07-24 12:34
@astefanutti do we need to place code inside $GOPATH/src
when i place it outside, the following error is occurs
operator-sdk build docker.io/apache/camel-k:1.0.0-M1-SNAPSHOT
FATA[0000] dependency manager "dep" requires working directory to be in $GOPATH/src

Before removing line 'go mod vendor' from make all was working fine.

**Comment by lburgazzoli** [comment] 2019-07-24 12:42
mh, go mod vendor should have been removed long ago

**Comment by dmvolod** [comment] 2019-07-24 12:44
@lburgazzoli it just removed 2 days ago by this commit
https://github.com/apache/camel-k/commit/2fb5fc54405851f684591fffabd0dfb519be27cd

**Comment by lburgazzoli** [comment] 2019-07-24 12:52
ah that one yes

**Comment by dmvolod** [comment] 2019-07-24 12:56
@lburgazzoli after this fix this issue occurs on my laptop.
Do you have suggestions related to it?

**Comment by astefanutti** [comment] 2019-07-24 12:56
@dmvolod it seems Go modules is deactivated somehow in your environment, and it still uses Dep, which requires the `vendor` directory.

Could you double check you environment variables and your Go version?

Do you have any `GOFLAGS=-mod=vendor?

**Comment by dmvolod** [comment] 2019-07-24 12:59
@astefanutti , just GOPATH and GO111MODULE
[dvolodin@dvolodin camel-k]$ export | grep GO
declare -x GO111MODULE="on"
declare -x GOPATH="/home/dvolodin/go"

**Comment by astefanutti** [comment] 2019-07-24 13:05
@dmvolod, what about `go version`?

I would try `export GO111MODULE="on"` instead of `declare -x GO111MODULE="on"` just in case 😄.

Anyhow, Go does not activate modules, hence your error, which is likely environment related.

**Comment by dmvolod** [comment] 2019-07-24 15:15
I tried different versions and after five into operator-sdk code, detects that our looking for the gopkg.toml file first. I deleted it and all becoming build fine.
@astefanutti, @lburgazzoli can we safely remove dep required files from repo?

**Comment by astefanutti** [comment] 2019-07-24 15:20
The only reason I know we've decided to keep the Dep files around is for the Knative eventing dependency on Camel K until it migrates to Go modules too: https://github.com/knative/eventing-contrib/blob/5ce18048c08b19437ac72fbdfeb4bf4a8d17c862/Gopkg.toml#L105.

It's weird it does not seems to reproduce on CI or locally for me 🤔. So there may be another way to work around this.

**Comment by dmvolod** [comment] 2019-07-24 15:27
Ok, will look into another workaround.
Maybe it's an OS/fedora regression.

**Comment by dmvolod** [comment] 2019-07-24 17:43
@astefanutti 
CI file still contains 'go mod vendor' command. Looks like this is a reason why CI is not failing.
I'm diving into operator-sdk code and the logic to detect of dependency manager is very simple and dep has priority.
https://github.com/operator-framework/operator-sdk/blob/d6e1aba9fa512ff9d441b648f548399c86929643/internal/util/projutil/project_util.go#L87-L104

May be I can't see very simple things.

**Comment by lburgazzoli** [comment] 2019-07-24 19:49
So I have the same issue and the CI does not fail because it does not use the operator-sdk but plain docker :) so I would suggest to apply the same logic in the makefile.

@astefanutti @nicolaferraro what do you think ?

**Comment by astefanutti** [comment] 2019-07-24 19:51
@dmvolod damn it seems my brain is throttling beyond 40ºC here, so I missed that `go mod vendor` in Travis config.

**Comment by astefanutti** [comment] 2019-07-24 19:51
@lburgazzoli I've created #872 (remove Dep files) which hopefully should make operator-sdk less confused about the history of Go dependencies management 😄.

**Comment by lburgazzoli** [comment] 2019-07-24 19:51
but it does not make any difference as operator-sdk is not used by the travis build :)

**Comment by lburgazzoli** [comment] 2019-07-24 19:53
Btw, I've created https://github.com/apache/camel-k/pull/871 to avoid `go mod vendor`

**Comment by dmvolod** [comment] 2019-07-25 06:28
@lburgazzoli , @astefanutti thanks.
I will report the issue and discuss it in operator-sdk upstream.

**Comment by astefanutti** [comment] 2019-07-25 08:57
Let me close this as it should be fixed with #872. Feel free to re-open if that is not the case.

**Closed by astefanutti** 2019-07-25 08:57 UTC

**Comment by astefanutti** [comment] 2019-07-25 08:58
@dmvolod thanks a lot for your valuable inputs on this. Let us know the outcome of the discussion upstream.

**Comment by aldettinger** [comment] 2019-07-25 09:40
make images-dev still produce the same error in my environment with operator-sdk v0.9.0, GO111MODULE=on and git up-to-date at commit 71557bd5d2ce55544fc0b677f9ac4681d985761b.

@dmvolod I'm considering reopening this issue. Could you please confirm that recent commits fixes make images-dev on your machine please ?

**Comment by dmvolod** [comment] 2019-07-25 09:53
@aldettinger, I'm fine with build right now.
Please pull latest master from upstream.

**Comment by aldettinger** [comment] 2019-07-25 09:54
It may be another issue then, I'll investigate that. Many thanks @dmvolod .

**Comment by dmvolod** [comment] 2019-07-25 11:56
https://github.com/operator-framework/operator-sdk/issues/1738
