### ISSUE TITLE
Flaky TestHealthTrait

### ISSUE THREAD

**Issue by christophd** [apache/camel-k#5345] opened 2024-04-10 08:29 UTC
### What happened?

The E2E test TestHealthTrait is flaky due to failing integration ready condition assertion in [health_test.go#L366](https://github.com/apache/camel-k/blob/main/e2e/common/traits/health_test.go#L366)

The E2E test starts an integration that should never become ready due to health traits. But at some point the Integration condition status is `ready=true` because for a short term period the Deployment ready state is reflected in the status:

```
- firstTruthyTime: "2024-04-09T20:36:38Z"
   lastTransitionTime: "2024-04-09T20:36:38Z"
   lastUpdateTime: "2024-04-09T20:36:38Z"
   message: 1/1 ready replicas
   reason: DeploymentReady
   status: "True"
   type: Ready
```

Shortly after that the Integration controller monitor will set the condition status to `ready=false` because of the health trait evaluation. This means there is a racing condition on the Integration ready status that causes the test to be flaky

### Steps to reproduce

See https://github.com/apache/camel-k/actions/runs/8620813154/job/23630392501?pr=5342

### Relevant log output

```shell
Camel K installed in namespace test-ce148498-46dd-4778-bf93-496d290c5607 
      health_test.go:366: 
          Failed after 9.120s.
          Expected
              <v1.ConditionStatus>: True
          to equal
              <v1.ConditionStatus>: False
```

### Camel K version

2.3.0

**Comment by squakez** [comment] 2024-04-10 08:34
I think it's a duplicate of #4922

**Closed by squakez** 2024-04-10 08:34 UTC
Labels: kind/bug

**Comment by christophd** [comment] 2024-04-10 08:36
@squakez good catch, thanks

**Comment by tdiesler** [comment] 2024-04-10 09:22
Can I take this?
