### ISSUE TITLE
KameletBinding in Error when prometheus trait is enabled

### ISSUE THREAD

**Issue by dmarrazzo** [apache/camel-k#3775] opened 2022-10-25 18:49 UTC
Hi all,

I'm trying to deploy a Kamelets which exposes custom metrics based on messages coming from kafka.
The KameletBinding works fine without the prometheus trait: the logs shows the expected behavior, but it does not expose the metric endpoint for scraping.

In this repository (ocp branch), you can find all the artifacts to reproduce the problem:

https://github.com/dmarrazzo/camel-quarkus-examples-metrics/tree/ocp

You can try the successful deployment commenting out those lines:

https://github.com/dmarrazzo/camel-quarkus-examples-metrics/blob/ocp/k8s/03-kafka-metrics-binding.yaml#L5-L6

Thank you

**Comment by squakez** [comment] 2022-10-26 07:21
Thanks for reporting. Tested on Camel K version `10.2`, likely a bug. Can you check if the same works against previous versions? ie, version `1.8`?

**Comment by dmarrazzo** [comment] 2022-10-26 09:23
Hello, I've tested in `1.8.2` and I have the same behavior. 
In that case if I remove the `trait` the build starts but it fails at runtime because the kamelet logic include that `jq` operand which is not supported in `1.8.2`.
I also did a different test applying the trait on a different KameletBinding (a very simple one: timer-log). In that case, the image build (integration kit) works and the kamelet exposes the metric endpoint without issues.

I suspect that this specific Kamelet fails because of the metric feature:

```yaml
  dependencies:
    - "camel:micrometer"
```


CC @lburgazzoli

**Comment by lburgazzoli** [comment] 2022-10-26 09:30
I think @dmarrazzo is right and the issue is related with the micrometer dependency because as today, if I'm not mistaking, we use mp-metrics for the prometheus trait hence there may be conflicts.

since mp-metrics is deprecated in favor of micrometer we should probably switch in camel k too

**Comment by squakez** [comment] 2022-10-26 09:34
Yes, we have an issue open about that: https://github.com/apache/camel-k/issues/1773. Is that dependency included in any of the Kamelet used? I wonder why we want to have it specified in the Kamelet instead of letting the operator in charge to manage that aspect accordingly.

**Comment by dmarrazzo** [comment] 2022-10-26 09:41
The reason is that the kamelet logic relies on that dependency: it adds a custom metric.
However, I believe that if someone else add that dependency a possible workaround could be removing it from the Kamelet.
I gonna test it and let you know soon.

**Comment by squakez** [comment] 2022-10-26 10:23
> The reason is that the kamelet logic relies on that dependency: it adds a custom metric. However, I believe that if someone else add that dependency a possible workaround could be removing it from the Kamelet. I gonna test it and let you know soon.

Okey, thanks. Could the custom metric be implemented with mp metrics while we don't move to micrometric?

**Comment by dmarrazzo** [comment] 2022-10-26 10:28
Hello @squakez, I confirm the workaround works:
https://github.com/dmarrazzo/camel-quarkus-examples-metrics/compare/ocp...dmarrazzo:camel-quarkus-examples-metrics:issue-3775-workaround

Thank you

I solved my specific use case, however, I believe this specific situation highlighted a weakness of the camel operator: the image build fails without a clue on the root cause (in this case a dependency clash).

Should I open a different issue or re-phrase this one?

**Comment by squakez** [comment] 2022-10-26 10:37
Yes, please, if the problem related to this issue is addressed, feel free to close it and open a new follow up issue.

**Closed** 2022-10-26 10:41 UTC
Labels: area/traits
