### ISSUE TITLE
Improve pipe status when the pod is full of exceptions

### ISSUE THREAD

**Issue by matzew** [apache/camel-k#4977] opened 2023-12-07 10:20 UTC
### Requirement

As a developer I want to see on the `k get pipes.camel.apache.org` if things are ok

### Problem

I have a broken `Kamelet`, in a pipe. see here for details: https://github.com/apache/camel-kamelets/issues/1785

The pod for that `aws-s3-source-pipe` is not working, since it is full of exceptions.

Now, checking the `pipe` status:
```
k get pipes.camel.apache.org 
NAME                 PHASE   REPLICAS
aws-s3-source-pipe   Ready   1
```

In fact the pipe is not ready, since its pod has an exceptions and it should be set to `ready:false`, with a `reason` for that, like other kube resources do.

As the reason some text from the exception could be used.

But in order to learn more about the error I have to check the log of the pod, and do not see this on a kube-native level (e.g. via CRs)

### Proposal

Reflect expection and do not set the status to `READY`, but report that it is **NOT** ready, and reason the exception details

**Comment by squakez** [comment] 2024-01-04 11:44
I had a look and this is what happening. The `Pipe` creates an `Integration` which finally ends up in spinning up a `Pod`. The `Pod` is tried to restart if it fails for certain reasons:
```
k get pods
NAME                                  READY   STATUS             RESTARTS      AGE
aws-s3-source-pipe-7568b69c9b-q9gzx   0/1     CrashLoopBackOff   6 (42s ago)   6m31s
```
So, the Integration, therefore the Pipe, are having a very short period of time, likely a few seconds while the Pod is trying to restart that is in Running state, but eventually turn to the correct error state:
```
$ k get pipe -w
NAME                 PHASE   REPLICAS
aws-s3-source-pipe   Error   1
aws-s3-source-pipe   Ready   1
aws-s3-source-pipe   Error   1
aws-s3-source-pipe   Ready   1
aws-s3-source-pipe   Error   1
aws-s3-source-pipe   Ready   1
aws-s3-source-pipe   Error   1
aws-s3-source-pipe   Ready   1
aws-s3-source-pipe   Error   1
```
I think this is the expected behavior in the sense that the Integration is running successfully until the Pod crashes. I am not sure if we can change this behavior, and, if that would make sense considering that eventually the Pipe and Integration are correctly set their status. Wdyt @lburgazzoli ?

**Comment by squakez** [comment] 2024-01-04 14:31
I applied a fix that should close this issue. However, that would work when the user defines a startup probe (via health trait for instance). The Integration (hence, the Pipe) won't be moved to the running phase until the Pod ready condition is reached.

**Comment by lburgazzoli** [comment] 2024-01-08 11:49
> 
> I think this is the expected behavior in the sense that the Integration is running successfully until the Pod crashes. I am not sure if we can change this behavior, and, if that would make sense considering that eventually the Pipe and Integration are correctly set their status. Wdyt @lburgazzoli ?

I think it all depends on the reason for which the POD fails, i.e.:
- in the past the pod was failing till some of the knative env vars were not injected and in such case we should probably improve the handling of such case
- if the pod crashes because i.e. fo a missing required parameter, then of course there is nothing we can really do (except maybe enabling route supervising by default for pipes)

what was the reason fro this Ready -> Error loop ?

**Comment by squakez** [comment] 2024-01-08 11:51
@lburgazzoli no, it was more a general problem in the order we were monitoring the Integrations. I found the root cause and applied a [fix under review right now](https://github.com/apache/camel-k/pull/5020). Thanks.

**Comment by lburgazzoli** [comment] 2024-01-08 11:52
ah ok, gogin on my backlog of notification so I'm not fully up to date yet :)

**Closed** 2024-01-08 16:05 UTC
Labels: area/observability
