### ISSUE TITLE
The --add-repo switch fails with a global operator

### ISSUE THREAD

**Issue by phantomjinx** [apache/camel-k#3667] opened 2022-09-22 12:33 UTC
The e2e test `TestKameletClasspathLoading` is executed, for OCP4, using a global operator. The test is currenty faiing with:
```
Warning: IntegrationPlatform "camel-k-kamelet" not found in namespace "test-86c0921d-4f78-4d9b-b1c9-e1c6a7bfe180"
Running as globally managed resource
Integration "timer-custom-kamelet-integration" created
=== CONT  TestKameletClasspathLoading
    kamelet_test.go:65: 
        Timed out after 600.002s.
        Expected
            <v1.PodPhase>: 
        to equal
            <v1.PodPhase>: Running
```

The clue is the warning, which occurs [here](https://github.com/apache/camel-k/blob/main/pkg/cmd/kamelet_add_repo.go#L85). Since the commands in the [test](https://github.com/apache/camel-k/blob/main/e2e/global/common/kamelet_test.go#L37) use an OperatorID, the integration platform that is installed in the namespace is not detected and hence the custom repo is not added. Therefore, the kamelet cannot be found in the custom repository and the integration fails with an error:
```
message: 'error during trait customization: kamelets [] found, [timer-custom-source]
      not found in repositories: (Kubernetes[namespace=test-279843cc-fcf7-4daa-bcf2-509cdb46b58d],
      Kubernetes[namespace=openshift-operators], Empty[])'
    reason: InitializationFailed
    status: "False"
```

Questions to consider:
1. The current e2e test suite continues to execute `kamel install` even if there is a global operator but in that use-case skips the operator itself and only installs the integration platform. Should this integration platform be passed the OperatorID -> see [here](https://github.com/apache/camel-k/blob/main/e2e/support/test_support.go#L246). This would fix the test but is this correct and cause breakages elsewhere?
2. Is there a bug here in that the `--add-repo` switch needs to support global operators?

**Comment by phantomjinx** [comment] 2022-09-22 12:33
@tadayosi
Would appreciate your views on this please.

**Comment by tadayosi** [comment] 2022-09-26 09:12
I'm not sure about what should happen if a global operator interacts with kamelet repos. Probably @christophd could answer better about the questions.

If it shouldn't work well with a global operator then it's just that `e2e/global/common` is not the right place to put the e2e test.

But my question is, why don't we observe the same failure at the upstream common CI?  This fact rather make me feel there might be some other root cause than the globalness of an operator, possibly specific to OpenShift.
https://github.com/apache/camel-k/actions/runs/3125524511

**Comment by phantomjinx** [comment] 2022-09-26 09:39
The reason lies in the use of OLM (or not upstream).

Upstream, the tests install the operator without OLM and therefore adds the correct operatorID (the test uses "[camel-k-kamelet](https://github.com/apache/camel-k/blob/main/e2e/global/common/kamelet_test.go#L36)". So the integration-platform is named with this id and the warning message above is avoided.

However, in OCP4, the OLM is used in the test. Since a global operator is installed, the operatorID is dropped from the install [request](https://github.com/apache/camel-k/blob/main/e2e/support/test_support.go#L292). This means the integration-platform installed in the namespace is named "camel-k" depsite the test assuming "camel-k-kamelet". Therefore, an integration-platform with the latter id is not found and the warning message is displayed, leading to the test failure.

**Comment by tadayosi** [comment] 2022-09-27 08:39
> Upstream, the tests install the operator without OLM and therefore adds the correct operatorID (the test uses "[camel-k-kamelet](https://github.com/apache/camel-k/blob/main/e2e/global/common/kamelet_test.go#L36)"). So the integration-platform is named with this id and the warning message above is avoided.

I don't think so. For upstream global e2e testing, `KamelInstallWithOperatorID()` also omits the operator ID so the IntegrationPlatform should be always `camel-k`:
https://github.com/apache/camel-k/blob/main/e2e/support/test_support.go#L246

As I understand it, when `CAMEL_K_FORCE_GLOBAL_TEST=true` is set, e2e tests always skip the operator ID part and use `camel-k` throughout the tests.

I think what's problematic is this line. Since it explicitly specifies `-x <operator-id>` it should happen to skip the `globalTest` guard provided by `Kamel*()` test support funcs. I wonder why upstream e2e still passes the test :thinking:
https://github.com/apache/camel-k/blob/main/e2e/global/common/kamelet_test.go#L65

**Comment by tadayosi** [comment] 2022-09-27 08:48
Maybe we should add a generic `KamelWithID(...)` and let it omit the operator ID for `kamel kamelet add-repo` command in the test.

**Comment by phantomjinx** [comment] 2022-09-28 09:27
> I don't think so. For upstream global e2e testing, `KamelInstallWithOperatorID()` also omits the operator ID so the IntegrationPlatform should be always `camel-k`: https://github.com/apache/camel-k/blob/main/e2e/support/test_support.go#L246

This is my bad explanation. We both agree on the issue that the IntegrationPlatform is named `camel-k` but the test calling `kamel run ... -x camel-k-kamelet ...` means the command searches for an IntegrationPlatform named `camel-k-kamelet` - see [here](https://github.com/apache/camel-k/blob/main/pkg/cmd/kamelet_add_repo.go#L85).

Therefore, I think question 2, above needs to be considered:
- Should the `add-repo` function:
  -- detect the installed IntegrationPlatform and compare operator ID. If they don't match, error out;
  -- attempt to find an IntegrationPlatform in ANY namespace with the given operatorID;
  -- drop the operatorID in the lookup of the IntegrationPlatform ([L85](https://github.com/apache/camel-k/blob/main/pkg/cmd/kamelet_add_repo.go#L85) above)

I am not sure that fixing the test is a way to mitigate this problem.

**Comment by tadayosi** [comment] 2022-09-29 04:58
I still think the test should be fixed, but also agree with your point that the `add-repo` sub command should be fixed as well. IMO the combination of the following two is the expected behaviour:
> -- detect the installed IntegrationPlatform and compare operator ID. If they don't match, error out;
> -- attempt to find an IntegrationPlatform in ANY namespace with the given operatorID;
Currently it tries to find IP only within a namespace and also only warns a log if it's not found, but it should search in all namespaces and throws an error when not found.

@essobedo @squakez What do you guys think about this?

**Comment by squakez** [comment] 2022-09-29 13:52
This was originally required to cover https://github.com/apache/camel-k/issues/2850. IMO, the command is just syntactic sugar for editing the IntegrationPlatform, so, I'd expect to look for the Integration platform in a given namespace and "attach" the repo specified. In case of a global operator, we still want to attach the repository to the IntegrationPlatform in the namespace required by the user, not necessarily globally.

**Comment by essobedo** [comment] 2022-10-04 10:35
I can check this one. How can I reproduce it?

**Comment by essobedo** [comment] 2022-10-05 12:33
Waiting for https://github.com/apache/camel-k/pull/3716

**Comment by essobedo** [comment] 2022-10-05 12:36
What I proposed as fix, is to keep the same behavior when the operator id is provided when it is not set I automatically detect the primary IP in the provided namespace and apply the change to it. WDYT?

**Comment by tadayosi** [comment] 2022-10-06 04:48
Sounds good to me, but then I'd like to make the `-x / --operator-id` behaviour consistent with other ID aware commands like `kamel run -x`. AFAIK `kamel run` doesn't have such a smart behaviour with `-x`.

**Closed** 2022-10-12 03:44 UTC
Labels: area/openshift
